on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: Build and publish release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v1
        with:
          go-version: 1.22

      - name: Checkout
        uses: actions/checkout@v1

      - name: Fetch dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Upload nat64
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_url.outputs.upload_url }}
          asset_path: nat64
          asset_name: nat64-${{ matrix.os }}-${{ matrix.gooarch }}
          asset_content_type: application/octet-stream

      - name: Upload dns64
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dns64
          asset_name: dns64-${{ matrix.os }}-${{ matrix.gooarch }}
          asset_content_type: application/octet-stream
